### ISSUE TITLE
task_id not provided

### ISSUE THREAD

**Issue by gsrigo** [RedHatSatellite/sat6_scripts#18]
have been looking at your code and if there are other sync processes running on the satellite when exporting, it will fail first withe the warning of Incomplete syn jobs detected, later will fail saying "Unable to start export - Sync in progress" but will be helpful if the script can spit out the task id that is preventing the export to run. Sometimes the satellite it gives the whole url for the task, in that way someone can go see it and unlock/stop it and the export job can be ran again

**Comment by ggatward** [comment]
Closing this issue...  It's not resolved as such, but the entire project has had significant development work on a private repo in a production environment, which has been ported to this public repo. This issue # conflicts with one from that repo, so I'm closing to avoid confusion.  

Please feel free to re-open if this is an issue on the updated codebase
