### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by arctiqjacob** [RedHatSatellite/sat6_scripts#22]
Getting an error when trying to export content:

Export Red_Hat_Satellite_Tools_6_2_for_RHEL_7_Server_RPMs_x86_64       (FULL)
  Waiting for export to complete...                                   
Traceback (most recent call last):
  File "./sat_export.py", line 1052, in <module>
    main(sys.argv[1:])
  File "./sat_export.py", line 882, in main
    os.chdir(exportpath)
OSError: [Errno 2] No such file or directory:

Looks like the function is trying to change into a directory that was never created.

**Comment by ggatward** [comment]
Hi,  This project has had significant development within a parallel private repo within a production environment. The private repo has now replaced the original sat6_disconnected_tools repo - I am closing this issue as I believe the problem you reported is resolved in the many commits made to the other repo, and should now be resolved in this one as well.   

Please feel free to re-open if it occurs again in the new codebase
