### ISSUE TITLE
Clean composite views before cleaning normal views

### ISSUE THREAD

**Issue by linuxabides** [RedHatSatellite/sat6_scripts#51]
Background:
I have the following content views:
Server 7
OpenShift
OpenShift Composite (Server 7 + OpenShift)

Issue:
When the clean_content_views script attempts to clean the OpenShift view before it has cleaned OpenShift composite it has the following error "WARNING: Failed to initiate removal (KeyError)". This is a result of the OpenShift view being required by the OpenShift Composite view.

Resolution:
Please clean composite views before cleaning regular views.

Thanks!

**Comment by linuxabides** [comment]
Confirmed. 2127e1b fixes this issue. Please accept changes to master.

**Comment by ggatward** [comment]
Thanks... Merged, have updated changelog in development branch.
