### ISSUE TITLE
export script - used /var/lib/pulp FS

### ISSUE THREAD

**Issue by benderase** [RedHatSatellite/sat6_scripts#53]
Hi there,
When I use the export script the Filesystem /var/lib/pulp is getting bigger, (be aware not the /var/lib/pulp/katello-export FS)
Is it a normal behave of the export?

**Comment by ggatward** [comment]
Hi....  is your katello-export a seperate mountpoint within /var/lib/pulp?   If your export path is  /var/lib/pulp/katello-export then that could explain what you are seeing as that is inside /var/lib/pulp.....
I generally set the export to a seperate mountpoint outside pulp  (/var/sat-export).   The export does however use /var/cache/pulp  which on some systems may be linked to  /var/lib/pulp/cache  when processing files, so this may grow as the export proceeds, but should reduce again as pulp empties the cache when done.

**Comment by benderase** [comment]
Hi, Thanks for the answer,
Yes the katello-export is on separated mointpoint.
you can see attached df output: (you can see that the export is even bigger then the source, seems wired too)
I was running the script sat_export.py --notar -a

/dev/mapper/rootvg-lv_cache_pulp  xfs       350G   34M  350G   1% /var/cache/pulp
/dev/mapper/rootvg-lv_lib_mongodb xfs        50G  2.3G   48G   5% /var/lib/mongodb
/dev/mapper/rootvg-lv_lib_pulp    xfs       1.7T  **297G**  1.4T  18% **/var/lib/pulp**
/dev/mapper/rootvg-lv_export      xfs       1.1T  **950G**  175G  85% **/var/lib/pulp/katello-export**

**Comment by benderase** [comment]
Hi, is there any update?

**Comment by ozchrisishere** [comment]
Hi,

Are you still having this issue? Are you able to list what is in the katello-export directory?

Cheers

Chris

**Comment by benderase** [comment]
Solved By redhat at a newer version of satellite.
